// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK5aN7qC8dRUELn2oFMDwK9q2vpx_2A7w',
    appId: '1:173125929838:web:1263c6f25b8f5382954f7f',
    messagingSenderId: '173125929838',
    projectId: 'new-version-nearme',
    authDomain: 'new-version-nearme.firebaseapp.com',
    storageBucket: 'new-version-nearme.firebasestorage.app',
    measurementId: 'G-W49ESWTEYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1uH3KIjNP3f8bPCwb8fFj6rmtlyMoEWM',
    appId: '1:173125929838:android:ed9728b1183251f4954f7f',
    messagingSenderId: '173125929838',
    projectId: 'new-version-nearme',
    storageBucket: 'new-version-nearme.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt1prIwAbdIzyYo1KpKY7l7laWi8eil_I',
    appId: '1:173125929838:ios:097c73a3455cd879954f7f',
    messagingSenderId: '173125929838',
    projectId: 'new-version-nearme',
    storageBucket: 'new-version-nearme.firebasestorage.app',
    androidClientId: '173125929838-bf2ll3s5dt9bo7ded862skjgen3k8v1b.apps.googleusercontent.com',
    iosClientId: '173125929838-ah0r62qhfqso1bi3qkna77g7bu6i7qhl.apps.googleusercontent.com',
    iosBundleId: 'com.example.nearMeNewVersion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt1prIwAbdIzyYo1KpKY7l7laWi8eil_I',
    appId: '1:173125929838:ios:7e43d0d0bfeb197e954f7f',
    messagingSenderId: '173125929838',
    projectId: 'new-version-nearme',
    storageBucket: 'new-version-nearme.firebasestorage.app',
    androidClientId: '173125929838-bf2ll3s5dt9bo7ded862skjgen3k8v1b.apps.googleusercontent.com',
    iosClientId: '173125929838-04b8a2i9oasuir98jnnqm3o24e9e6bl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.nearMeNewVersion.RunnerTests',
  );
}
